version: '3.1'
services:
  zookeeper-server:
    image: zookeeper
    restart: always
    ports:
      - '2181:2181'
      - '8080:8080'
    environment:
      ZOO_ADMINSERVER_ENABLED: true
  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=shortener
      - MONGO_INITDB_ROOT_USERNAME=shortener_api_user
      - MONGO_INITDB_ROOT_PASSWORD=ysoasmxmskmoIUGI
